# Generated by Django 5.1rc1 on 2024-08-03 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='language',
            table='languages',
        ),
    ]
